### ISSUE TITLE
[FIXED] 404 WebSocket Upgrade Failure

### ISSUE THREAD

**Issue by deltatron7543** [mesacarlos/WebConsole#122]
added the plugins to my 1.19 papermc servers plugins folder along with a few other plugins, i change the config file to what is below and when i try to go to the website over same network it says "404 WebSocket Upgrade Failure"

```
useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: storepassword
KeyPassword: keypassword
host: 192.168.1.244
port: 8080
language: en
passwords:
  admin:
    Deltatron:
      password: verysecure
      commandWhitelist:
        enabled: false
        commandWhitelistActsAsBlacklist: false
        whitelist:
        - whisper
        - gamemode survival
  viewer: {}
```

Edit: im smooth brain, didnt realize that you had to use a actual client webpage and not just the IP of the server, very smooth brain moment
