### ISSUE TITLE
How to add a viewer correctly?

### ISSUE THREAD

**Issue by SkyKingPX** [mesacarlos/WebConsole#140]
I tried too many times and it still doesn’t work. 
can someone make an example config.yml?

**Comment by mesacarlos** [comment]
Hello,
Here is an example:

```
useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: mypassword
KeyPassword: mypassword
host: 0.0.0.0
port: 8080
language: en
passwords:
  admin:
    mesacarlos:
      password: mesacarlos-password
      commandWhitelist:
        enabled: true
        commandWhitelistActsAsBlacklist: true
        whitelist:
        - whisper
        - gamemode survival
  viewer:
    ViewerUser: password
    AnotherViewerUser: password2
```
