### ISSUE TITLE
It keeps asking me for password

### ISSUE THREAD

**Issue by EmpathyHeals** [mesacarlos/WebConsole#35]
The password required window keeps popping up over and over and won't let me log in.

[![Screenshot from Gyazo](https://gyazo.com/86aadaf647cd416fe2f65150f9a8b988/raw)](https://gyazo.com/86aadaf647cd416fe2f65150f9a8b988)

**Comment by mesacarlos** [comment]
Hello,
What version are you using? Is this your first install of the plugin or you updated to 2.0 from a v1.x version?

**Comment by mesacarlos** [comment]
I'm closing this issue as solved.
If someone is here with the same issue and you just upgraded from v1.x to v2.0, remember that this new version changes the structure of your config.yml and **you NEED to change the login password from it current location to the new place**. Read README.md for more info.

### Example:
The modification is simple. If your config.yml was like this (v1.x):

useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: storepassword
KeyPassword: keypassword
host: localhost
port: 8080
**password: yourPasswordGoesHere**
language: en


You only need to remove that line completely (or leave it, it will do nothing) and type it there along with an username:
```
useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: storepassword
KeyPassword: keypassword
host: 0.0.0.0
port: 8080
language: en
passwords:
   admin:
      YourUsername: yourPasswordGoesHere
   viewer: {}
```

That modification will leave WebConsole working as usual. At this point you can continue adding more users below.
