### ISSUE TITLE
I can't connect to the server

### ISSUE THREAD

**Issue by kirillopnytop** [mesacarlos/WebConsole#38]
![index html](https://user-images.githubusercontent.com/63828171/86026600-d95fa080-ba59-11ea-983a-00145b7f1802.png)
![index html#](https://user-images.githubusercontent.com/63828171/86026606-d9f83700-ba59-11ea-9aca-efa3962e8573.png)
![Opera Снимок_2020-06-29_223928_craft-hosting ru](https://user-images.githubusercontent.com/63828171/86026611-da90cd80-ba59-11ea-9e82-ce344ef24638.png)

**Comment by mesacarlos** [comment]
try replacing the host field of your config.yml to 0.0.0.0

**Comment by kirillopnytop** [comment]
and on the site what to write too 0.0.0.0

**Comment by mesacarlos** [comment]
no, only config.yml

**Comment by kirillopnytop** [comment]
does not work

**Comment by mesacarlos** [comment]
Is the IP of the website correct? If the server is hosted in your computer, try using localhost instead.

Also, i noticed that you have a `password` field. Maybe you followed an outdated guide, because that field is no longer used by webconsole v2.0. In v2.0 you need to use the admin: section, so the configuration is something like:
```
useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: storepassword
KeyPassword: keypassword
host: 0.0.0.0
port: 8282
language: ru
passwords:
   admin:
      kirillopnytop: TEST
   viewer: {}
```
