### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by XxPKBxX** [mesacarlos/WebConsole#66]
![image](https://user-images.githubusercontent.com/29917385/111025919-b1b73980-842a-11eb-9bf6-3f2f7e59dead.png)

I have enabled all of possible ports: WebConsole, [WebServer](https://dev.bukkit.org/projects/webserver/), and my server port.
Why is this happening? In local console, nothing shows.
But browser consoles shows this:
```WebConsoleConnector.js?v=2.1.0:25 WebSocket connection to 'ws://myip:5855/' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE```

**Comment by mesacarlos** [comment]
Hi,

If you get that error, it seems that the port you use is open and reachable.
Please recheck that you have SSL disabled in your server (it seems to be disabled in your client) and recheck that the port you are connecting to is the WebConsole port.

**Comment by XxPKBxX** [comment]
```
useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: storepassword
KeyPassword: keypassword
host: 0.0.0.0
port: 5857
language: en
passwords:
  admin:
    admin: admin
  viewer: {}
```
I think SSL is disabled
